# Parameter bounds
N_bounds = [3,12]                  # Lower and upper bounds
Ro_bounds = [6,6]                  # Equal bounds freezes the parameter
#Ri_bounds = [4.9,5.9]
#Rp_bounds = [3.0,4.8]
Ri_bounds = [1.0,5.9]
Rp_bounds = [1.0,5.9]
f_bounds = [0.1,1.0]
epsilon_bounds = [0.1,0.9]
halfTheta_bounds = [0.6,1.0]
length_bounds = [24,24]

# Nozzle properties
expansion_ratio=8
ambient_pressure=14.7
exit_pressure=14.7
throat_diameter=2.0
exit_diameter=12                  # Embedded nozzle; Re = Ro

# Case design properties
safety_factor=1.3
mass_fraction=0.85

## Evolution settings
generations = 60                  # Number of generations
pop_size = 10                     # Individuals in each generation

## Single-optimization settings
fitness_function = 'max_pressure' # Parameter to be optimized
maximize = true                   # Maximize or minimize the parameter
viz = false                       # Display fitness plot
history = false                   # Print all individuals, not just winner
hard_bounds = true                # Keep offspring within original bounds

## Multiple-optimization settings
std = 1.0                         # Standard deviation for Gaussian mutation
expected_num_mutations = 'isotropic'
selector = 'tournament'           # Selection method (random or tournament)